name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.13.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - notebook
  - matplotlib
  - numpy
  - vpython

  - jupyter=1.0.0
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - ipykernel
  - ipywidgets=7.5.1
  - nbconvert=5.6.1
  - notebook=6.4.1
